package com.cubeos.meshsat.crypto

import android.content.Context
import android.util.Base64
import com.cubeos.meshsat.data.AppDatabase
import com.cubeos.meshsat.data.ConversationKey
import com.cubeos.meshsat.data.ProviderCredential
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Imports key bundles from meshsat://key/ URLs generated by the MeshSat bridge.
 *
 * Bundle binary format:
 * Version(1) | BridgeHash(16) | Timestamp(4) | EntryCount(1) | Signature(64)
 * Per entry: ChannelType(1) | AddrLen(1) | Address(N) | AESKey(32)
 */
object KeyBundleImporter {

    private const val URL_PREFIX = "meshsat://key/"
    private const val HEADER_SIZE = 22 // version(1) + bridgeHash(16) + timestamp(4) + count(1)
    private const val SIGNATURE_SIZE = 64
    private const val AES_KEY_SIZE = 32

    private val CHANNEL_TYPES = mapOf(
        0x00.toByte() to "sms",
        0x01.toByte() to "mesh",
        0x02.toByte() to "iridium",
        0x03.toByte() to "astrocast",
        0x04.toByte() to "zigbee",
        0x05.toByte() to "mqtt",
        0x06.toByte() to "webhook",
    )

    /**
     * Import keys from a meshsat://key/ URL.
     * Stores each key entry as a ConversationKey (for per-channel encryption)
     * and as a ProviderCredential (for credential management).
     *
     * @return Number of keys imported.
     */
    suspend fun importFromURL(url: String, context: Context): Int {
        require(url.startsWith(URL_PREFIX)) { "Not a meshsat key URL" }

        val encoded = url.substring(URL_PREFIX.length)
        val data = Base64.decode(encoded, Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)

        require(data.size >= HEADER_SIZE + SIGNATURE_SIZE) { "Bundle too short" }

        // Parse header
        val version = data[0]
        require(version == 0x01.toByte()) { "Unsupported bundle version: $version" }

        val bridgeHash = data.sliceArray(1..16)
        val timestamp = ByteBuffer.wrap(data, 17, 4).order(ByteOrder.BIG_ENDIAN).int.toLong() and 0xFFFFFFFFL
        val entryCount = data[21].toInt() and 0xFF

        // Skip signature verification for now (would need bridge's Ed25519 public key)
        // TODO: TOFU — on first scan, store bridge signing pub for future verification

        // Parse entries
        var offset = HEADER_SIZE + SIGNATURE_SIZE
        val db = AppDatabase.getInstance(context)
        val convKeyDao = db.conversationKeyDao()
        val credDao = db.providerCredentialDao()
        var imported = 0

        for (i in 0 until entryCount) {
            require(offset + 2 <= data.size) { "Truncated entry $i" }
            val channelType = data[offset]
            val addrLen = data[offset + 1].toInt() and 0xFF
            offset += 2

            require(offset + addrLen + AES_KEY_SIZE <= data.size) { "Truncated entry $i data" }
            val address = String(data, offset, addrLen, Charsets.UTF_8)
            offset += addrLen

            val aesKey = data.sliceArray(offset until offset + AES_KEY_SIZE)
            offset += AES_KEY_SIZE

            val hexKey = aesKey.joinToString("") { "%02x".format(it) }
            val channelName = CHANNEL_TYPES[channelType] ?: "unknown"
            val bridgeHashHex = bridgeHash.joinToString("") { "%02x".format(it) }

            // Store as ConversationKey (for message encryption)
            convKeyDao.upsert(
                ConversationKey(
                    sender = address,
                    hexKey = hexKey,
                    label = "Bridge $channelName (${bridgeHashHex.take(8)})"
                )
            )

            // Store as ProviderCredential (for credential management)
            credDao.upsert(
                ProviderCredential(
                    id = "${bridgeHashHex.take(8)}_${channelName}_${address.hashCode().toString(16)}",
                    provider = channelName,
                    name = "Key for $address (bridge ${bridgeHashHex.take(8)})",
                    credType = "aes_key",
                    encryptedData = aesKey, // stored raw — Android Keystore protects DB at rest
                    source = "qr",
                    version = 1,
                )
            )

            imported++
        }

        return imported
    }
}
